/*
A KBase module: kb_metabolic
*/

module kb_metabolic {

    /* A boolean - 0 for false, 1 for true.
        @range (0, 1)
    */
    typedef int boolean;

    /* An X/Y/Z style reference
    */
    typedef string obj_ref;

    /*
        required params:
        assembly_ref: Genome assembly object reference
        input_binned_contig_names: list of BinnedContigs object names
        output_binned_contig_name: output of BinnedContig names
        workspace_name: the name of the workspace it gets saved to.

        optional params:
        search_engine; default diamond
        score_threshold; default 0.5
        duplicate_penalty; default 0.6
        megabin_penalty; default 0.5
        write_bin_evals; default 1
        create_plots; default 1
        write_bins; default 1
        write_unbinned; default 0
        ref: https://github.com/cmks/DAS_Tool

    */
    typedef structure {
        obj_ref assembly_ref;
        list<obj_ref> input_binned_contig_names;
        string output_binned_contig_name;
        string workspace_name;

        string search_engine;
        float score_threshold;
        float duplicate_penalty;
        float megabin_penalty;
        int write_bin_evals;
        int create_plots;
        int write_bins;
        int write_unbinned;
    } DASToolInputParams;

    /*
        result_folder: folder path that holds all files generated by run_kb_metabolic
        report_name: report name generated by KBaseReport
        report_ref: report reference generated by KBaseReport
    */
    typedef structure{
        string result_directory;
        obj_ref binned_contig_obj_ref;
        string report_name;
        string report_ref;
    } DASToolResult;

    funcdef run_kb_metabolic(DASToolInputParams params)
        returns (DASToolResult returnVal) authentication required;

};
